/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DynamicComponent {
    }
}
declare global {
    interface HTMLDynamicComponentElement extends Components.DynamicComponent, HTMLStencilElement {
    }
    var HTMLDynamicComponentElement: {
        prototype: HTMLDynamicComponentElement;
        new (): HTMLDynamicComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dynamic-component": HTMLDynamicComponentElement;
    }
}
declare namespace LocalJSX {
    interface DynamicComponent {
    }
    interface IntrinsicElements {
        "dynamic-component": DynamicComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dynamic-component": LocalJSX.DynamicComponent & JSXBase.HTMLAttributes<HTMLDynamicComponentElement>;
        }
    }
}
